f_burst_pharma = figure('Position', [488 1.8000 680.3150 857.9636],...
    'Color','w');

plot_log = 1;
norm_idx = 0;

base_width = 0.11;
bar_width = 0.06;
base_space = 0.06;
height_space = 0.0417;
graph_height = 0.14;

n_spikes_min = 1;

pos_ax = [0.1 0.2549 base_width graph_height];

input_idx = 1;
all_1x_n_spikes = {all_pharma_n_spikes1{input_idx},...
                    all_pharma_n_spikes2{input_idx},...
                    all_pharma_n_spikes3{input_idx},...
                    all_pharma_n_spikes4{input_idx}};
[ax_pharm_n1] = UBC_par_line_plot(...
    select_cells,[],all_1x_n_spikes,[norm_idx plot_log 0],n_spikes_min,f_burst_pharma,pos_ax,...
    [1 2 3 4]);
ylabel("Response spikes (n)")
% title('1x')


pos_ax(1) = sum(pos_ax([1,3]))+base_space;
input_idx = 2;
all_2x_n_spikes = {all_pharma_n_spikes1{input_idx},...
                    all_pharma_n_spikes2{input_idx},...
                    all_pharma_n_spikes3{input_idx},...
                    all_pharma_n_spikes4{input_idx}};
[ax_pharm_n2] = UBC_par_line_plot(...
    select_cells,[],all_2x_n_spikes,[norm_idx plot_log 0],n_spikes_min,f_burst_pharma,pos_ax,...
    [1 2 3 4]);
% title('2x')

pos_ax(1) = sum(pos_ax([1,3]))+base_space;
input_idx = 3;
all_5x_n_spikes = {all_pharma_n_spikes1{input_idx},...
                    all_pharma_n_spikes2{input_idx},...
                    all_pharma_n_spikes3{input_idx},...
                    all_pharma_n_spikes4{input_idx}};
[ax_pharm_n3] = UBC_par_line_plot(...
    select_cells,[],all_5x_n_spikes,[norm_idx plot_log 0],n_spikes_min,f_burst_pharma,pos_ax,...
    [1 2 3 4]);
% ylabel("Response spikes (n)")
% title('5x')


pos_ax(1) = sum(pos_ax([1,3]))+base_space;
input_idx = 4;
all_10x_n_spikes = {all_pharma_n_spikes1{input_idx},...
                    all_pharma_n_spikes2{input_idx},...
                    all_pharma_n_spikes3{input_idx},...
                    all_pharma_n_spikes4{input_idx}};
[ax_pharm_n4] = UBC_par_line_plot(...
    select_cells,[],all_10x_n_spikes,[norm_idx plot_log 0],n_spikes_min,f_burst_pharma,pos_ax,...
    [1 2 3 4]);
% title('10x')

pos_ax(1) = sum(pos_ax([1,3]))+base_space;
pos_ax(3) = base_width + bar_width;
input_idx = 5;
all_20x_n_spikes = {all_pharma_n_spikes1{input_idx},...
                    all_pharma_n_spikes2{input_idx},...
                    all_pharma_n_spikes3{input_idx},...
                    all_pharma_n_spikes4{input_idx}};
[ax_pharm_n5] = UBC_par_line_plot(...
    select_cells,[],all_20x_n_spikes,[norm_idx plot_log 1],n_spikes_min,f_burst_pharma,pos_ax,...
    [1 2 3 4]);
% title('20x')


all_axes = {ax_pharm_n1, ax_pharm_n2, ax_pharm_n3, ax_pharm_n4, ax_pharm_n5};
arg_names = {'XScale', 'XTickLabel'};
% val_pairs = {'linear',    {'Baseline','−mGluR2','−AMPAR','−mGluR1'}};
val_pairs = {'linear',    {''}};
arg_names{end+1} = 'XLabel';
val_pairs{end+1} = xlabel('');


set_to_axes(all_axes,arg_names,val_pairs)
% for ii = 1:numel(all_axes); all_axes{ii}.YLim(1) = 0; end


amp_min = 1;

pos_ax(1) = 0.1;
pos_ax(2) = pos_ax(2)-graph_height-height_space;
pos_ax(3) = base_width;


input_idx = 1;
all_1x_amp = {all_pharma_slow_amp1{input_idx},...
                    all_pharma_slow_amp2{input_idx},...
                    all_pharma_slow_amp3{input_idx},...
                    all_pharma_slow_amp4{input_idx}};
[ax_pharm_amp1] = UBC_par_line_plot(...
    select_cells,[],all_1x_amp,[norm_idx plot_log 0],amp_min,f_burst_pharma,pos_ax,...
    [1 2 3 4]);
ylabel('Peak (\Deltaspk/s)')


pos_ax(1) = sum(pos_ax([1,3]))+base_space;

input_idx = 2;
all_2x_amp = {all_pharma_slow_amp1{input_idx},...
                    all_pharma_slow_amp2{input_idx},...
                    all_pharma_slow_amp3{input_idx},...
                    all_pharma_slow_amp4{input_idx}};
[ax_pharm_amp2] = UBC_par_line_plot(...
    select_cells,[],all_2x_amp,[norm_idx plot_log 0],amp_min,f_burst_pharma,pos_ax,...
    [1 2 3 4]);

pos_ax(1) = sum(pos_ax([1,3]))+base_space;

input_idx = 3;
all_5x_amp = {all_pharma_slow_amp1{input_idx},...
                    all_pharma_slow_amp2{input_idx},...
                    all_pharma_slow_amp3{input_idx},...
                    all_pharma_slow_amp4{input_idx}};
[ax_pharm_amp3] = UBC_par_line_plot(...
    select_cells,[],all_5x_amp,[norm_idx plot_log 0],amp_min,f_burst_pharma,pos_ax,...
    [1 2 3 4]);


pos_ax(1) = sum(pos_ax([1,3]))+base_space;

input_idx = 4;
all_10x_amp = {all_pharma_slow_amp1{input_idx},...
                    all_pharma_slow_amp2{input_idx},...
                    all_pharma_slow_amp3{input_idx},...
                    all_pharma_slow_amp4{input_idx}};
[ax_pharm_amp4] = UBC_par_line_plot(...
    select_cells,[],all_10x_amp,[norm_idx plot_log 0],amp_min,f_burst_pharma,pos_ax,...
    [1 2 3 4]);

pos_ax(1) = sum(pos_ax([1,3]))+base_space;
pos_ax(3) = base_width + bar_width;
input_idx = 5;
all_20x_amp = {all_pharma_slow_amp1{input_idx},...
                    all_pharma_slow_amp2{input_idx},...
                    all_pharma_slow_amp3{input_idx},...
                    all_pharma_slow_amp4{input_idx}};
[ax_pharm_amp5] = UBC_par_line_plot(...
    select_cells,[],all_20x_amp,[norm_idx plot_log 1],amp_min,f_burst_pharma,pos_ax,...
    [1 2 3 4]);



all_axes = {ax_pharm_amp1, ax_pharm_amp2, ax_pharm_amp3, ax_pharm_amp4,...
    ax_pharm_amp5};
arg_names = {'XScale', 'XTickLabel'};
val_pairs = {'linear',    {'Baseline','−mGluR2','−AMPAR','−mGluR1'}};
% val_pairs = {'linear',    {''}};
arg_names{end+1} = 'XLabel';
val_pairs{end+1} = xlabel('');

set_to_axes(all_axes,arg_names,val_pairs)
same_ylim(all_axes)